import common.Fasta
import java.security.InvalidParameterException
import java.util.*

/**
 * Created by egslava on 27/7/16.
 */

object GC_content {
    val dataset     = """
        >Rosalind_8432
        CACTAGGTAGCACACGCATGCTCAGCCCTGGCGCTTACTTGCAGGCCATGGTCGTCTGAC
        TGGCCAATACTATACGAATCCCCCACTGCTTTAGTCTTTCCCTCGGGGCCAATCCGTTAC
        CCAGGTCTGTTTGGCCGCTCTGAGGACGCTCAGCCTAATGAACGTCGTGCGGATCAGACA
        GTACATCCAAAGTGACCCCTCGAGCTATCCAGTGGAGCCTGGCCAAGTTTGGGGATTAGC
        TATGTACGTAAGACGGATATTTTCGCCGAATGTCGGTGCGTAGGCAGACTGGCTAAAGCG
        CACATGCCGCGGTGCGGTCTCTCAGGACGCGTGCCGCATCTCATGCTTGGTACAGACACT
        CCGTGCGGTGGTTAACACATACTTGTTCGTGGCAATGAACCCTCTAGCCTGCGGGAAATG
        CAAAATGGGCGAAAGCCGGGTCGGAACACGCTGTAGGTTTGGGATAGATAAAACATAGCA
        AACTCACCGTGATAGTATCCTACCTCAGCAAGGTTCAAGAACCACGGCCGCACCACGTCG
        GAACACGACACGAGGGAAGGATCTCAATGGGCCACATCAACTTGCCAAATGACTCATGAC
        TTGCGAAGTGAAGCTAGTAGACCCAACCCAGCCACATTTATGATATGCGCGGTGAGAGTG
        CGACCTTCCGTGTAACTCCGTCTAAGACAGTGGTGCCGTTAGGTCAATCTGGCAAGTGTT
        TAGGACAATCCAAAACTCCTTCTACATGAGTGTTGACTGTGGACACGACCTTACTTGCAG
        TGCCGCTCTATAGACCTAACATAGTATCGTTTCGATGACAGTGAAAACAGCGCGAGGAGC
        ATAGGTG
        >Rosalind_9594
        TTTTCTACTAGGCAGACGCTCCGTGCACTATAGAAACCACAAGGTTGCTCGGCTCATGGA
        TGCCGGAGATAAAGGCGCGGTTCATCCCTTTACGGGAACGAAGATCGAAGAGATGAACCC
        GAGCGATACCACATGATCTGGACGGTTTGCGGCTCGGACCTGCTCCACGATGTTTTGAGG
        CGTCTTAAGGTGGAATGAAGTAATGCGTTATGCCCATTGCGCTGGAGTCCAACCTGGATA
        TTATGTTGCACGTTCCAACTAGAAGATCTTAGGGGCTGTGGTGGAGCTATAGCATACGAC
        ACGTAACGCAGGTAGAGATCCGGGATAAGTGAGCGCCTTGCGCGCGCGCATCCTAGAATC
        TCTGGATAGCTAATCGGGCCGTCGGGCGACTCTCACCAGGAGATCCTTTAGCAAGCACTC
        TAGTGAGACTCTAAGACGTCAGGTAATGGGCTGCTGGCATCTAAGTGATCAATAGAGTTT
        AAAGATCTATTAATCAAATTTCTTCGTAGCCGAATGACCAATGAATTGCCGGAACGATTT
        AACGGCAAGGTCACTCTCTCTTCATTGGCAGGGGCAACCCCTAACTTCTCGATTTCAAAA
        ACTTCTCTAAAGAGCTCTTTAGATGGTACGTCTTCCCTGTCTTGGGGCCTGATGTGGGCC
        CGCCCGTACCATATTCCGGGCGTGGACCTCTTGTAAGGCGGCTATCCTTATCGCATATCC
        GAGGCGATATTTTCCGTTGTACCGGTCAGTTTTACTGAGGAGAACAACACGTGTAATACC
        ATCCATCCCGCTGAAATAAGATTCAGGGGAGGCAGGCTGAGATCCAGTCTTCAGAACGGT
        TCCCAGGGAGGCGGCACGGAAATTGGGATTTCTATTGCGGGCCCTGCGCGTGGCTGGAGA
        GGGGACCTATCAATGTGTTGCGATACACTTTAACTGGCAACTTTCTCCAGATGACAACCC
        CACCTACCCCACGAAGGGAACAT
        >Rosalind_2288
        CCATACCTAACCCGTAGCTTGTCTACTCAGGATAATCCATTATCGCCGTGGTATTAGGTT
        CAAGAAAAAGAGGGTTCCTCAGGGGTATTTTCCTTGGGCCCACTATGCGGTACCGCATAA
        CGAACACTTTCCTATGCGCGGTGCATGGATGAGAGCCTGTCATTACTGTACGAGACACTG
        CTTCTTCAGTACCCCCCCGTAATGCGCGGTGAGCTGCACCGCGCTTGACTCAGTTTGTTA
        TCTTCTGGTAGACTGTTCAAGGACTTAGACAGGGAATACATGGAGTTGAGACTAAGAAAT
        TTTACTTGTTATGTCTTGGTTGTGGCGGTTCACGTACCGTTACTCCCTTGTTTTTTCAAC
        CAGAAATCGTTGTCCACTAATCTGATGCAGTCCTACGCGCGCTAGTTCACGCTCAGTGTG
        TGTTTCTCAATATCTATGACCATGATAACTCTTTTGTTTTAAGACAAGCCCTTCCCTATC
        ACAGTCTGGTCATGGTTTGGGCTGCTCAGAGTGGTGCTAGTAAAAATGAAGACGACTCTT
        TGTTGCCGTAGGTCAGTGCTCGAGGGCGTTAGCCATTTAATTAAAGTTCCAGACTACTAA
        AATAACGTCGGGCGAGGAAACCAAGCTGTACTCGATGGTGCCAACATCGAACAAGTGAAT
        CATAGGCCTCACCAATCTTAGACTACAGACACCTTCGTAGATGGGGCGGATTTTTCCGCG
        TATGTGATGCGTGTCGGAGTGTCTCTACGACCTGGACTCGGCCCCTACGTACTCGACTCA
        GTATCTCGCTTACGTGCGCGACTGCGCGATGATGTTCCT
        >Rosalind_3611
        TAGGTAACTTGACCACAAGCTGTAGTCTAACGGTGCCGCTAGTCCTTAAGTTATGTAACT
        TTTGTTGCCGAACGGCAGCGGCTGTTTTCTAGTGCTAGCTACGGAGATAGCCAGTTTGCG
        CCATACCCGTGTTTGAAACCTATAAGCGCAATGACCACCCCTTCGGTCCTACCTTACCTT
        GTGTAGGGCGCGAGTTCGTTGTGTACAGTCGCGCAATGGGCAGCCATCCTAGGTTCCAAT
        GGCCGGCTGCCGATTAATACGGTCGGAGTCCCCCACTAACCACAAGGGCCGACTGGTAGA
        CACTCATGTCAAAGAGTGCCGTTGTCACGGCACTATGGATGTCTTTCAACGGTGACATAC
        CTGTTTAGCACTAGTTTTCGGTAGTCAGGTGATTAGGACTACCTGAACATACAGGGGCGA
        ACCGACGTTAGAGGCTTACGTCGTATCATATGAGAGATGACGATGGTCTTAAATCGTTAA
        GCTGGATACTCCCTAATGTCGTGGTCGGCTGTAAACCATTGGCTAACGAGAGCTGTATCG
        GAACTAGAAGTACACTCTAACGGAAAAGACCATATCTAACGAAGATACGGAACTGAGTAC
        AAGCAGTCTGCCTACCGTTTTTGTCGTGTGCTAGACGGGCAGCGTTCGTCCCTTGTCGGT
        GGGAGTGTATTGTATAAACCGCAGGAACGTTAGCGGACGGCCGAGTGCCTATTCCTCGCT
        TTTATGGGCAACTCCCTCGTAGGTTTTTTACTCACGGAGTCGTCGCAGTGGCCGTGACGC
        AGGCCCGGTATGGATACCAACGACCCTTTTTCGTGGCAGGAATCAACCCTCTTGATGATA
        ATTATGTGACTTACAGTGTTTAGCACAAGACACCCCTGGAACTACTGGTGACGGGTCAGT
        GGGAAATCTTGTCGGGCCGACGGTAAACCCGGGGTTGGAATATAAATG
        >Rosalind_8435
        TCTGGCCGCTTTAAACGCCATTTATGGACGCACCCACCCGCGATGCGACCTTCCTGCGGA
        AATCTCTGGTACTAGCGAACACGGAAAGACACCCTCCGTAGATTGCCTATTATGCGGTCA
        GTTCATCTCAGTGGCTCCTTGGATCCTATCACTGGGACGATAGTTTCCCTTGTTTAGCAG
        CAGTAGCTATTAAGCTGTTGCTAAACCTGACATGGAGACGCTCCTACATAGGCCACGTAT
        AATCCGGGAATGCCGGTCAGCAGGCTGCAGATTTGGACTACGGTTGCAAACAGTCTTGGG
        TCCTACGTAAATTAAAGGTATTATGTTCCCGCGTTATCATCGCTTCTGTAATGCCTCTGA
        GACCCCTCATTACCTTCGGTCCAGTCCGTGAATCAAAGGGTGGGTAACCCGTACACGGGG
        TATTGTTGTCTGGTGTTTATTCGGACTAGACATGAAGTCAGGCAGGTGAGTGTCAGCAAA
        TAGAAGACATGAGGCAGGGAATTCTGTACGCATCCCCTTCTATCCCCAACTGGGACTCGC
        AGGAGGATTGGTTCCTACTATTCTAAATAATAAGTGTTGCGGGCAAGCTGACCGCCTCAT
        ATGAGTTCAAGTCGGATTACCTCTTGATAACATATGTTACTGTGAGACCTCATTTGTTTG
        AGTGGCCGTGCGCACAACCTTTGTTATTAACTATCGTTCCCCCGGTGTCGGTGCCAGTCG
        GCCCGTGCAAGGACGTCGCACAACCGTTTAGCAATTGCAAGTTATAGTCACTGCAGAACA
        CCTCTACATTGCAGCTCAGTGTTCCCGTAATAGACCACTAGATATGGTTACTTCTCTAAT
        ATCGGGTCAAGCATGATAGCCCTCCGAGG
        >Rosalind_5679
        ACTCGGCAAGGACTCGCCTTTACCAGCCATTACTGCGCGAGTATACGGAACAGTGCACCG
        CCTTATAAGAGGCCAGTCCTTATCGTAGGAAGCCCACGACTCCTGCCGCGTCGCAAAAGA
        AGAACGGTAATGGTTGTACACCCCACATGGAACGACAGCCACAACGTGGGGCAAGTGCCC
        ACTTGTGTAGGTCTACAACAGCTCACCAATCTCGGAGAAGGCATATTCTAGATCGTAATA
        TGCCCAGTACTCGGCGTGAGAACCTAGTTACTCAATCATTCCTTTGCCACCGTTGTATCG
        CCGATAACACTAACATGGGGCATGTTCTGTCATAGGAATATACTCTCCACCGTCTAATAA
        AAATGGCACTCTGACATAGGTGCCTGGCCCAGGGGATACTCAACAAAAGGATTTTTCCCT
        TGCTAAAGCTCCCAAGGGCTAACGCTTGCACAAGGCGCCACGAATTTGTTACAGTGGCGC
        AATAATTGGCAGCGAGAGACTACTGCGGCCAATCCTAGCCGGTGCATTTGTATACCAACA
        CGCTAGTAATGTTGGGAGTCGGTATATTATGCCCCGGGCCCCGGAGAGAACCAAAGAATC
        ATCACGGTATTACCCGCCGGTGGAAGTTTTCGGTTAGGGTGAAGTGCAGCCAGTGGGTCA
        GCAAGGGGGAATGAAGCAGTAACAGCATACCGTTGCTGCCCGTTCCCCTGAGTAAGCAGA
        TCAGCGGACTATCGACATACCGTGAACTCTGGTATGTCTCCGCAAGAATTGAACTAGTCC
        AACGAATATCGAGTTACTCCAACCCTTAGGCGATCGTCCACTTCTGCTCGTCCTTGACCT
        GGCGGTACACGCGATACCGAACTGCCTGACCCTAGTGCCTTCATGTAACGAGGCGGCGCC
        ACTGATCCAATGCCTAACCGGGTCGGTCTATCAGTCTATGATAAATTGTTTACCGTCGAC
        GAATAT
    """.trimIndent().trim()


    @JvmStatic fun main(args: Array<String>) {
        val DNAs = Fasta.parse(dataset).sortedByDescending { it.gcContent }

        println(DNAs[0].renderAsResult())
    }
}
