/**
 * Created by egslava on 3/7/16.
 * http://rosalind.info/problems/list-view/
 */


object Main {
//    val dataset = """CACGTGACGTTAGCGTCCCCGATGCGGAACTTAGGAAGGTGACATACCAGTGCTTGTTTCTCTCGTCCACATGATGGGCTTGTATCCCCCGTAGAAGGAGGCGTGTGCTCTCACGAGGGCTGCTCGGTACCTGCGTTACCCGGAGTTGATTCGTTTCCCTAACCACATTGCGTGTTCTAAATGTGCTGTGCTATGACAGCAGGGGCTTTGACTAACGAGGACTAGATTTCGACCCAAAGGTAATATCCTTCTCCGGAGACACGGAACGGACGAATACGAAAACACTAACATCGATTTGAATATTTTGTGTATCCCTTAAACAGAGTGTGTACCTACAAGGCAGTAATCAGGGTGTCAGTCGGGCGCAAACACCCTCACTGACATGTACAGGGAAGTAGTAGTCTCTATCCTGAGTGCACACAAGAGAGGTAGCGAGCATTTTGAGGTAAGATGGAACCTAAGTTGTTGCGAGGCAGAAAACAATTACTCCGCGATTCATACTCCGTTTGAACGTGTTGTCAAGTCTTGCTTCCACGACCTAAATATCCGCAATTCGAATGGCATTGTGTTCTGTGACGTCATTGAGACTGCGTAGAAAAAAATTGCACTATGGGACTGCGAACCTCTAATGCGTGATGTCAGCCGCGATGGACCAGGGTCTTTGAGATAACACTAGGAAGCCCGCATTGTAGCAGCACCGAGTTGGGGCTAGCAAATGCTAGTGTCAGATGCCGAGGTTATCGTAATAACTCAGAACTAAGGTAAGGCGAAGTTTTATTTTCCGACCATCCCTCATCCTGAGACCGTCCCCGTGGTCCCATTCCCGCGAACTCAACATTCGCCCTACCGACACTAAGCTCTCAATTCCAAGCGGTTCT"""
    val dataset = """GGAGAAAGGCGCTGTGTTCAAGGCTTAAAACTGCTGATGATTCACGTATATAAATGCGTGGGATGTAATTTATTACGATCAAAGTGCGCGCGGGGCTGAAGAACAAGTGACCAGCATGGCGCCAGGTGGATGAAACAAAGCCACGTAATTTCAGGTAAGATAGAATGTAGTTGTATTACATGTTACGGGTCCATATAAGCAGTATAGAACCTAACAGCCGGGAATCGCCCCCGTCCGCCACGTGCAGAGCAGTGTAAGATACCCTTAGCAGACGCCAAACCATGCCGGTGGGTGGCTGAGAGGCTCCTACTATGAGATGCTGCCTAGGCGGTAGAGTTGAACTATCACTCCTAAGGATTAGGAGGTCTGCCTAAGTGCCGTAATATCGGCCTCAGCCACTTCTAAGTTTCACAAAGGCGCGCACTACGTGGGAGAAGGGCACAGAGGGCTAGTCCATTTCATATCGAGGCAAGAGCACGTTAAGGCGAAAGGATACTAGCGCGTACAGCTACAACGCCCTCACTGTTGACAATAGCGATTGTGCAGTTAACTAGCTTGAAGTGAGTAATCATGGATATCGGTCTGAGCAGCGTTGCGTGCACTCTGCAGGCCGTGTCCGAAGTTACCCCTTGCGCTCTAATAGCCAGTAAGCTTCCAGAACGGTGCAGTTGCAGAATGGACTTGCGCCGGATTCACGACCGACACCGATTTAACGGCGCGCCCGCTTTGATCCTTTTAAGAACACAGGCACTTCCCAGGGTCGGTTAGTTACATTCGTTCGCTAACTGCTTATGACCAGTTGTGACACCTGACCCCTAGCCCTTTTGAGAAGGTGGATAAAAATCCGCAGGCGCTATTTATGGATAGTATCCACCCGCGCTGAGCTTGGGAGGACGCTCTACGTTTTCACACTGGGTGCC"""

    @JvmStatic fun main(args: Array<String>) {
        var a = 0
        var c = 0
        var g = 0
        var t = 0
        for (char in dataset) when (char) {
            'A' -> a += 1
            'C' -> c += 1
            'G' -> g += 1
            'T' -> t += 1
        }

        // 1, 1, 2, 3, 5, 8, 13, 21
        println ("$a $c $g $t")
    }
}
